FROM python:3.9.0-slim-buster

RUN apt-get -y update

RUN apt-get -y install apt-utils

RUN apt-get -y install postgresql

RUN apt-get -y install gcc

RUN apt-get -y install git

RUN apt-get -y install make

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN pip install gunicorn